### PR TITLE
Add support for running rsc with kawa scheme

### PR DESCRIPTION
**Pull request by shawnw**
Includes Kawa-optimized versions of some of the runtime compatibility layer functions, and breaks up some of the larger `cond-expand` blocks into smaller more organized chunks, to make it easier to add support for more schemes (And improve current ones; I want to add some Chicken-specific versions of functions too next)

### CODE REVIEW

**Comment by feeley** [comment]
Thanks for your pull request.  I notice that now the `rsc` script requires `$RSC_SCHEME_INTERPRETER` to be set rather than defaulting to `gsi`.  I will fix that.

**Comment by shawnw** [comment]
Yeah, there was a hardcoded gsi in it. Causes problems if you don't have gambit installed. Figured it was better to use the same scheme interpreter everything else was using in a run of the script.

**Comment by feeley** [comment]
There are still uses of `gsi` in the minification pipeline (when the `-m` command line option is used).  Ideally the Ribbit system should be standalone, only depending on a POSIX shell to work.  The `minify.scm` program can remain a Scheme program but run it with `sh prebuilt/repl-max.sh` (or use a precompiled version) if a Scheme system is not installed (this will require porting `minify.scm` to Ribbit Scheme).

**Comment by feeley** [comment]
The `minify.scm` program is a general purpose program that does a few simple transformations on source code to make it more compact.  Essentially it removes comments and whitespace, and finds programmer-introduced identifiers and replaces them with shorter ones allocated from the sequence `a`, `b`, ...  For example for lua the `minify.scm` program is called like this (in the `src/host/lua/minify` script that is called by `rsc`):

```
gsi `dirname "$0"`/../../minify.scm \
--ident-chars "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ_0123456789" \
"local" "function" "end" "break" "while" "=" "return" "if" "then" "else" "elseif" "type" "'table'" "io" "stdout" "write" "string" "char" "flush" "not" "byte" "stdin" "read" "true" "do" "or" "math" "floor" "os" "exit"
```

This will shorten the identifiers in the lua program, except for `local`, `function`, `end`, etc that remain the same.

The `minify.scm` program should be rewritten as a shell script for greater portability.  Another option would be to remove it and move that functionality to `rsc`.

**Pull request merged**
